AWSTemplateFormatVersion: 2010-09-09
Resources:
  CloudFormation:
    Type: 'Community::SecurityHub::Insight'
    Properties:
      InsightName: test
      GroupByAttribute: ResourceType
      Filters: '{
                "AwsAccountId": [
                    {
                        "Value": "306473543633",
                        "Comparison": "EQUALS"
                    },
                    {
                        "Value": "644005288616",
                        "Comparison": "EQUALS"
                    },
                    {
                        "Value": "892248855080",
                        "Comparison": "EQUALS"
                    },
                    {
                        "Value": "883790930938",
                        "Comparison": "EQUALS"
                    }
                ],
                "ComplianceStatus": [
                    {
                        "Value": "FAILED",
                        "Comparison": "EQUALS"
                    }
                ],
                "WorkflowStatus": [
                    {
                        "Value": "SUPPRESSED",
                        "Comparison": "NOT_EQUALS"
                    }
                ],
                "RecordState": [
                    {
                        "Value": "ACTIVE",
                        "Comparison": "EQUALS"
                    }
                ]
            }'
      