AWSTemplateFormatVersion: 2010-09-09

Resources:
  StandardsControlIAM6:
    Type: 'Community::SecurityHub::StandardsControl'
    Properties:
      StandardCode: AFSBP
      ControlId: 'IAM.6'
      ControlStatus: 'DISABLED'
      DisabledReason: Root user doesnt have a password
