AWSTemplateFormatVersion: 2010-09-09

Parameters:
  instanceArn: 
    Type: String
    Default: arn:aws:sso:::instance/ssoins-7223bb1f3d5cae54

  principalId: 
    Type: String
    Default: 906761b815-8d376b7c-4306-4c61-9536-0076e38d9499

Resources:

  TestPS:
    Type: AWS::SSO::PermissionSet
    Properties: 
      Name: TestPSABC
      Description: Readonly Access
      InstanceArn: !Ref instanceArn
      ManagedPolicies: 
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      SessionDuration: PT12H

  TestAssignmentGroup:
    Type: Community::SSO::AssignmentGroup
    Properties:
      InstanceArn: !Ref instanceArn
      PermissionSets:
      - !Ref TestPS
      PrincipalId: !Ref principalId
      PrincipalType: GROUP
      Targets:
      - TargetType: AWS_ACCOUNT
        TargetIds:
        - '102625093955'